apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
  namespace: app
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - Example.com
  commonName: client-cert
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - "*.app"
  issuerRef:
    kind: ClusterIssuer
    name: gemfire-ca-issuer
    group: cert-manager.io
  secretName: client-cert
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: client-cert